add getter and setter for output path
render-engine/render-engine pull request #592
Opened 2024-02-15 12:50 UTC by john0isaac

# Type of Issue

- [ ] :bug: (bug)
- [ ] :book: (Documentation)
- [ ] :arrow_up: (Update)
- [X] :dizzy: (New Feature)
- [ ] :radioactive: (Deprecation)
- [ ] :no_entry_sign: (Removal)
- [ ] :hammer_and_wrench: (Refactor)

fix #585

2024-02-18 00:18 UTC, kjaymiller requested changes

2024-02-18 00:18 UTC, kjaymiller commented on src/render_engine/site.py
> +        self.theme_manager.static_paths = static_paths
This doesn't seem to ensure that the paths are in a set.

2024-02-19 22:37 UTC, john0isaac commented on src/render_engine/site.py
> +        self.theme_manager.static_paths = static_paths
fixed

2024-02-21 22:21 UTC, kjaymiller approved these changes

2024-02-22 00:46 UTC, merged